name: wassword
description: Wassword - Wonderful Password Generator

version: 2.0.2+11

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^7.1.0
  equatable: ^2.0.3
  flutter_bloc: ^7.2.0
  fluttertoast: ^8.0.8
  google_fonts: ^2.1.0
  share_plus: ^2.1.4
  url_launcher: ^6.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.2.3

#dependency_overrides:
  #args: ^2.1.1

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/icona/
